language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
script:
  - cd tests; py.test --cov ampcountpy
install:
  - pip install codecov pytest pytest-cov coverage
  - python setup.py install
after_success:
  - codecov
